version: "3"

networks:
  docker_network:
    driver: bridge
    name: docker_network

services:
  node:
    restart: always
    build: .
    ports:
      - 3002:3002
    volumes:
      - ./:/code
    depends_on:
      - mongo
    networks:
      - docker_network
  mongo:
    image: mongo:7.0
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27018"]
    ports:
      - 27018:27018
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'host.docker.internal:27018'}]}) }" | mongosh --port 27018 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
    volumes:
      - mongodb:/data/
  swagger-ui:
    depends_on:
      - node
    image: swaggerapi/swagger-ui
    container_name: swagger_ui_container_pedido
    ports:
      - "81:8081"
    volumes:
      - ./swagger:/usr/share/nginx/html/swagger
    environment:
      API_URL: /swagger/openapi.yaml
    networks:
      - docker_network
volumes:
  mongodb:
